// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3JgINGHRDHeLIQQNeaGI-TBa-KV_u4TQ',
    appId: '1:186710268609:web:5bcef59677077c55079240',
    messagingSenderId: '186710268609',
    projectId: 'login-auth-c6651',
    authDomain: 'login-auth-c6651.firebaseapp.com',
    storageBucket: 'login-auth-c6651.firebasestorage.app',
    measurementId: 'G-FZ0HQEDGKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7jT1ojryoR0-d0zln-ycRs5mTr4JZthI',
    appId: '1:186710268609:android:cc642a267fbe3ae8079240',
    messagingSenderId: '186710268609',
    projectId: 'login-auth-c6651',
    storageBucket: 'login-auth-c6651.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJfmMkPPDnMWRsevtCBvCXxAWtcbFbZSg',
    appId: '1:186710268609:ios:afcf798772b9414e079240',
    messagingSenderId: '186710268609',
    projectId: 'login-auth-c6651',
    storageBucket: 'login-auth-c6651.firebasestorage.app',
    iosBundleId: 'com.example.loginAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJfmMkPPDnMWRsevtCBvCXxAWtcbFbZSg',
    appId: '1:186710268609:ios:afcf798772b9414e079240',
    messagingSenderId: '186710268609',
    projectId: 'login-auth-c6651',
    storageBucket: 'login-auth-c6651.firebasestorage.app',
    iosBundleId: 'com.example.loginAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3JgINGHRDHeLIQQNeaGI-TBa-KV_u4TQ',
    appId: '1:186710268609:web:2c460c420b4f795c079240',
    messagingSenderId: '186710268609',
    projectId: 'login-auth-c6651',
    authDomain: 'login-auth-c6651.firebaseapp.com',
    storageBucket: 'login-auth-c6651.firebasestorage.app',
    measurementId: 'G-X7QP44LT74',
  );
}
